### ISSUE TITLE
Use StumpWM config to update Polybar

### ISSUE THREAD

**Issue by jcf** [lepisma/cfg#1]
Hi Abhinav, 

Just wanted to say a quick thank you for sharing your Polybar StumpWM groups module. With it I've been able to work out the IPC necessary to update my groups in my Polybar in near-realtime. Thanks!

One thing I did slightly differently that you may be interested in was I used a function in my StumpWM config that I called via `stumpish` like so:

``` sh
stumpish eval "(jcf/polybar-stumploc)"
```

That meant I could use structural editing etc. because the Lisp was in Lisp buffer rather than [inside a string in a shell script](https://github.com/lepisma/cfg/blob/master/polybar/.config/polybar/stumpwmgroups.sh).

Anyway, thanks again!

**Comment by jcf** [comment]
Closing as this isn't a problem. Just wanted to say thanks, and share a potential improvement.

**Comment by lepisma** [comment]
Thanks! I moved that snippet in Lisp file. Feels much cleaner now!
